# Generated by Django 5.1.1 on 2024-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_variation_variation_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("size", "size"), ("color", "color")], max_length=100
            ),
        ),
    ]
