# Generated by Django 3.1 on 2024-09-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
