# Generated by Django 5.1.1 on 2024-10-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="types",
            field=models.CharField(
                choices=[("user", "user"), ("business", "business")],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
