# Generated by Django 5.1.1 on 2024-10-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="types",
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("user", "user"), ("business", "business")],
                default="user",
                max_length=20,
            ),
        ),
    ]
