# Generated by Django 5.1.1 on 2024-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("user", "user"), ("business", "business")],
                default="user",
                max_length=20,
            ),
        ),
    ]
