# Generated by Django 5.1.1 on 2024-10-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_account_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bname", models.CharField(max_length=40)),
                ("btype", models.CharField(max_length=40)),
                ("baddress", models.CharField(max_length=40)),
                ("bpostalcode", models.CharField(max_length=40)),
                ("bcity", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, default=None, upload_to="userprofile"),
        ),
    ]
