# Generated by Django 5.1.1 on 2024-10-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_businessdetails_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessdetails",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
